version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./test-sql-2:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: null
